### PR TITLE
Add pagination for sketches

### LINKED ISSUE #78: Pagination for the Sketch page
@nikochiko, we need to have pagination in the sketch page as we had for the [submission](https://mon.school/code-a-pookkalam/submissions) of code-a-pookkalam. Can you look into this?

### PR DESCRIPTION
**Pull request by nikochiko**
Fixes #78 

**Changes:**
* Added pagination for `mon_school/sketches`
* Screenshot (with 3 total sketches and a limit of 2 sketches per page):
image

### CODE REVIEW

**Comment by nikochiko** [comment]
I think the CSS didn't load properly for me on the local setup hence the blue color instead of the green as on the mon school page. (Noticed the `Submit a Sketch` button with the same color issue too).

With the CSS elements, the blue will change to same green as on the code a pookkalam page. (https://mon.school/code-a-pookkalam)

**Comment by nikochiko** [comment]
@wisharya @anandology please have a look.

**Comment by anandology** [comment]
> 



> I think the CSS didn't load properly for me on the local setup hence the blue color instead of the green as on the [mon school page](https://mon.school/sketches). (Noticed the `Submit a Sketch` button with the same color issue too).

that is perfectly alright. Those css changes are only part of the website theme and not part of the repo.

**Comment by nikochiko** [comment]
As of now, it will show all the 100 page numbers.
As discussed, I'll look into options to reduce that to something that makes more sense.

For now I'm liking how Google does it (showing 10 relevant pages):
image

On going to the 7th page, it would show pages from 2 to 11, and so on.

For sketches, I think it would make sense to show either a limited number of pages or only the next/previous buttons since the sketches are all random (i.e. no filters/search params). The navigating user can hit next as many times as they are curious to see more sketches.

**Comment by nikochiko** [comment]
Have added pagination window of 5 pages. At any page, it will try to show 5 relevant pages if possible.

image

image

image

**Review by anandology — APPROVED** [review]
LGTM!

**Pull request merged**
